name: effort

on:
  push:

jobs:
  initiate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grocery: ["certainty", "abstract", "intelligence", "menu", "degree"]
        lumber: ["balcony", "fancy", "receiver", "postpone"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java --enable-native-access=ALL-UNNAMED -jar xi.jar
